[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Content-Type" = "text/css; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    "X-Content-Type-Options" = "nosniff"